### ISSUE TITLE
CKAN pre 2. to 2.9+/2.10.x Migrate Package activity.

### ISSUE THREAD

**Issue by duttonw** [qld-gov-au/ckan#151]
Looking into json dict issues on sqlalchemy with caching, came accross the activity should be going away via https://github.com/ckan/ckan/pull/3972/files
more details on: 
https://github.com/ckan/ckan/wiki/Migrate-package-activity 

for our purposes this worked
```
cd /mnt/local_data/ckan_venv/src/ckan/
sudo -u ckan wget https://raw.githubusercontent.com/ckan/ckan/master/ckan/migration/migrate_package_activity.py
sudo -u ckan wget https://raw.githubusercontent.com/ckan/ckan/master/ckan/migration/revision_legacy_code.py
sudo mv  ckan/migration/revision_legacy_code.py  ckan/migration/revision_legacy_code.py.bak
sudo cp revision_legacy_code.py  ckan/migration/revision_legacy_code.py
sudo -u ckan /mnt/local_data/ckan_venv/bin/python migrate_package_activity.py -c /etc/ckan/default/production.ini
```

next step would be to investigate on cleaning up the old table to reduce sqlalchemy slowness since delta/history now lives in new location.

**Comment by ThrawnCA** [comment]
NB There wasn't any need for wget. The files are already checked out at `/mnt/local_data/ckan_venv/src/ckan/ckan/migration`
